name: video_editor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastapi=0.104.1
  - uvicorn=0.24.0
  - python-multipart=0.0.6
  - ffmpeg=6.0.0
  - ffmpeg-python=0.2.0
  - jinja2=3.1.2
  - aiofiles=23.2.1
  - pytest=7.4.3
  - python-jose=3.3.0
  - requests=2.31.0
  - pip=23.3.1
  - pip:
    - python-multipart==0.0.6 